#!/bin/bash -l
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -t 00:06:30
#SBATCH --mail-user=kirk.larsen@berkeley.edu
#SBATCH -A m2218
#SBATCH -o jacobi_1.%j.stdout
#SBATCH -e jacobi_1.%j.error

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun -n 2 -c 32 --cpu_bind=cores ./jacobi
