#!/bin/bash -l
#SBATCH -N 2         #Use 2 nodes
#SBATCH -t 00:30:00  #Set 30 minute time limit
#SBATCH -p debug   #Submit to the regular 'partition'
#SBATCH -L SCRATCH   #Job requires $SCRATCH file system
#SBATCH -C haswell   #Use Haswell nodes
#OpenMP settings:

export OMP_PLACES=threads
export OMP_PROC_BIND=spread


export OMP_NUM_THREADS=4

time srun -n 4 -c 4 -C haswell --cpu_bind=threads ./jacobi > runs/test_2node_4core_4omp.out

export OMP_NUM_THREADS=4

time srun -n 2 -c 4 -C haswell --cpu_bind=threads ./jacobi > runs/test_2node_2core_4omp.out
