#!/bin/bash
#SBATCH -N 2
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -J alowell_astro250_hw2_int_exp
#SBATCH -t 00:20:00

#OpenMP settings:
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:

#the ~5 minute run
export OMP_NUM_THREADS=1
time srun -n 2 -c 32 --cpu_bind=cores ./int_exp

#the second run with 2 full nodes of mpi, just one thread
export OMP_NUM_THREADS=1
time srun -n 64 -c 2 --cpu_bind=cores ./int_exp

#1/6
export OMP_NUM_THREADS=2
time srun -n 64 -c 2 --cpu_bind=cores ./int_exp

#2/6
export OMP_NUM_THREADS=4
time srun -n 32 -c 4 --cpu_bind=cores ./int_exp

#3/6
export OMP_NUM_THREADS=8
time srun -n 16 -c 8 --cpu_bind=cores ./int_exp

#4/6
export OMP_NUM_THREADS=16
time srun -n 8 -c 16 --cpu_bind=cores ./int_exp

#5/6
export OMP_NUM_THREADS=32
time srun -n 4 -c 32 --cpu_bind=cores ./int_exp

#5/6
export OMP_NUM_THREADS=64
time srun -n 2 -c 64 --cpu_bind=cores ./int_exp


